CREATE TABLE IF NOT EXISTS inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL check (quantity >= 0),
    reserved_quantity INT NOT NULL check (reserved_quantity >= 0),
    CHECK (reserved_quantity <= quantity)
);